#!/usr/bin/env ruby
#^syntax detection

require 'certified'

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'nodejs'
cookbook 'build-essential'
cookbook 'ruby_build'
cookbook 'rbenv'
cookbook 'site',
         :path => 'site-cookbooks/site'
cookbook 'mysql'
cookbook 'mysql2_chef_gem'
cookbook 'database'
